export const languages = { en: 'English', ru: 'Русский', kk: 'Қазақша', de: 'Deutsch', fr: 'Français', es: 'Español', zh: '中文', ja: '日本語', ko: '한국어', tr: 'Türkçe' };
export const currencies = ['KZT', 'USD', 'EUR', 'GBP', 'RUB', 'CNY', 'JPY', 'KRW', 'INR', 'TRY'];
const rows = `
storageLimit|Limit: 500 templates and 4 MB of template data. Export a backup, then remove unused templates.|Лимит: 500 шаблонов и 4 МБ данных шаблонов. Скачай копию, затем удали ненужные шаблоны.|Шек: 500 үлгі және 4 МБ үлгі деректері. Көшірмені жүктеп, қажетсіз үлгілерді жой.|Limit: 500 Vorlagen und 4 MB Vorlagendaten. Sicherung exportieren, dann ungenutzte Vorlagen löschen.|Limite : 500 modèles et 4 Mo de données. Exportez une copie puis supprimez les modèles inutilisés.|Límite: 500 plantillas y 4 MB de datos. Exporta una copia y elimina las que no uses.|上限：500个模板及4 MB模板数据。请导出备份后删除不用的模板。|上限は500件、4 MBです。バックアップを書き出し、不要なテンプレートを削除してください。|한도: 템플릿 500개, 데이터 4 MB. 백업 후 불필요한 템플릿을 삭제하세요.|Sınır: 500 şablon ve 4 MB veri. Yedek alıp kullanılmayan şablonları sil.
ruleType|Rule type|Тип правила|Ереже түрі|Regeltyp|Type de règle|Tipo de regla|规则类型|ルールの種類|규칙 유형|Kural türü
confirmConflict|“{name}” changed or was deleted in another tab. Save your draft instead?|«{name}» изменён или удалён в другой вкладке. Сохранить вместо него твой черновик?|«{name}» басқа қойындыда өзгертілді не жойылды. Орнына нобайың сақталсын ба?|„{name}“ wurde in einem anderen Tab geändert oder gelöscht. Stattdessen deinen Entwurf speichern?|« {name} » a été modifié ou supprimé ailleurs. Enregistrer votre brouillon à sa place ?|«{name}» cambió o se eliminó en otra pestaña. ¿Guardar tu borrador en su lugar?|“{name}”已在另一标签页更改或删除。改为保存你的草稿？|「{name}」は別のタブで変更または削除されました。下書きで置き換えますか？|“{name}”이 다른 탭에서 변경되거나 삭제되었습니다. 내 초안으로 저장할까요?|“{name}” başka sekmede değiştirildi veya silindi. Yerine taslağın kaydedilsin mi?
brandNote|Your money, your priorities|Твои деньги, твои приоритеты|Өз ақшаң, өз басымдықтарың|Dein Geld, deine Prioritäten|Votre argent, vos priorités|Tu dinero, tus prioridades|你的钱，你的优先事项|お金を、あなたの優先順位で|내 돈, 나의 우선순위|Paran, önceliklerin
calculate|Calculate|Рассчитать|Есептеу|Berechnen|Calculer|Calcular|计算|計算する|계산|Hesapla
templates|Templates|Шаблоны|Үлгілер|Vorlagen|Modèles|Plantillas|模板|テンプレート|템플릿|Şablonlar
settings|Settings|Настройки|Баптаулар|Einstellungen|Réglages|Ajustes|设置|設定|설정|Ayarlar
intro|Give every payment a plan|Деньги пришли. План уже есть.|Ақша түсті. Жоспар дайын.|Ein Plan für jeden Geldeingang|Un plan pour chaque rentrée d’argent|Un plan para cada ingreso|让每笔收入都有计划|収入に、いつもの計画を|수입마다 계획을 세우세요|Her gelir için bir plan
introText|Choose a template and enter the amount. Rules run from top to bottom.|Выбери шаблон и введи сумму. Правила выполняются сверху вниз.|Үлгіні таңдап, соманы енгіз. Ережелер жоғарыдан төмен орындалады.|Vorlage wählen, Betrag eingeben. Regeln gelten von oben nach unten.|Choisissez un modèle et un montant. Les règles suivent leur ordre.|Elige una plantilla y un importe. Las reglas se aplican en orden.|选择模板并输入金额。规则从上到下依次执行。|テンプレートを選び金額を入力。ルールは上から順に適用されます。|템플릿과 금액을 선택하세요. 규칙은 위에서 아래로 적용됩니다.|Şablon seç ve tutarı gir. Kurallar yukarıdan aşağıya uygulanır.
template|Template|Шаблон|Үлгі|Vorlage|Modèle|Plantilla|模板|テンプレート|템플릿|Şablon
amount|Incoming amount|Сумма поступления|Түскен сома|Eingegangener Betrag|Montant reçu|Importe recibido|收入金额|入金額|수입 금액|Gelen tutar
choose|Choose a template|Выбери шаблон|Үлгіні таңда|Vorlage wählen|Choisir un modèle|Elige una plantilla|选择模板|テンプレートを選択|템플릿 선택|Şablon seç
newTemplate|New template|Новый шаблон|Жаңа үлгі|Neue Vorlage|Nouveau modèle|Nueva plantilla|新建模板|新規テンプレート|새 템플릿|Yeni şablon
empty|Your first plan starts here|Здесь появится твой первый план|Алғашқы жоспарың осында болады|Hier beginnt dein erster Plan|Votre premier plan commence ici|Tu primer plan empieza aquí|从这里开始第一个计划|最初の計画を作りましょう|첫 계획을 시작하세요|İlk planın burada başlıyor
emptyText|Add fixed amounts and percentages in priority order. Reuse the plan for your next income.|Добавь суммы и проценты по приоритету. Используй план при следующем поступлении.|Сомалар мен пайыздарды басымдықпен қос. Келесі кірісте осы жоспарды қолдан.|Feste Beträge und Prozente nach Priorität anlegen. Beim nächsten Einkommen wiederverwenden.|Ajoutez montants et pourcentages par priorité. Réutilisez le plan au prochain revenu.|Añade importes y porcentajes por prioridad. Reutiliza el plan con el próximo ingreso.|按优先级添加固定金额和百分比，下次收入时再次使用。|固定額と割合を優先順に登録。次の収入でも使えます。|고정 금액과 비율을 우선순위대로 추가하고 다음 수입에도 사용하세요.|Sabit tutarları ve yüzdeleri öncelik sırasıyla ekle. Sonraki gelirde tekrar kullan.
percentHint|Percentages use the remaining balance, not the initial amount.|Проценты считаются от остатка после предыдущих правил.|Пайыздар алдыңғы ережелерден кейінгі қалдықтан есептеледі.|Prozente beziehen sich auf den verbleibenden Betrag.|Les pourcentages portent sur le solde restant.|Los porcentajes se calculan sobre el saldo restante.|百分比以之前规则执行后的余额为基数。|割合は各ルール適用後の残額に対して計算します。|비율은 앞선 규칙 적용 후 잔액을 기준으로 합니다.|Yüzdeler önceki kurallardan sonra kalan tutara uygulanır.
name|Template name|Название шаблона|Үлгі атауы|Vorlagenname|Nom du modèle|Nombre de plantilla|模板名称|テンプレート名|템플릿 이름|Şablon adı
ruleName|Rule name / note|Название правила / заметка|Ереже атауы / ескертпе|Regelname / Notiz|Nom de règle / note|Nombre de regla / nota|规则名称／备注|ルール名・メモ|규칙 이름 / 메모|Kural adı / not
fixed|Fixed amount|Фиксированная сумма|Тұрақты сома|Fester Betrag|Montant fixe|Importe fijo|固定金额|固定額|고정 금액|Sabit tutar
percentage|% of remaining|% от остатка|Қалдықтың %-ы|% vom Rest|% du solde|% del saldo|余额的百分比|残額の％|잔액의 %|Kalanın %’si
value|Value|Значение|Мәні|Wert|Valeur|Valor|数值|値|값|Değer
addRule|Add rule|Добавить правило|Ереже қосу|Regel hinzufügen|Ajouter une règle|Añadir regla|添加规则|ルールを追加|규칙 추가|Kural ekle
save|Save|Сохранить|Сақтау|Speichern|Enregistrer|Guardar|保存|保存|저장|Kaydet
cancel|Cancel|Отмена|Бас тарту|Abbrechen|Annuler|Cancelar|取消|キャンセル|취소|İptal
edit|Edit|Изменить|Өзгерту|Bearbeiten|Modifier|Editar|编辑|編集|편집|Düzenle
delete|Delete|Удалить|Жою|Löschen|Supprimer|Eliminar|删除|削除|삭제|Sil
up|Move up|Поднять|Жоғары жылжыту|Nach oben|Monter|Subir|上移|上へ|위로|Yukarı taşı
down|Move down|Опустить|Төмен жылжыту|Nach unten|Descendre|Bajar|下移|下へ|아래로|Aşağı taşı
move|Move to template|Перенести в шаблон|Үлгіге көшіру|In Vorlage verschieben|Déplacer vers un modèle|Mover a otra plantilla|移至模板|別のテンプレートへ|다른 템플릿으로 이동|Şablona taşı
position|Position|Позиция|Орны|Position|Position|Posición|位置|位置|위치|Konum
rules|Rules|Правила|Ережелер|Regeln|Règles|Reglas|规则|ルール|규칙|Kurallar
noRules|No rules yet|Правил пока нет|Әзірге ережелер жоқ|Noch keine Regeln|Aucune règle|Aún no hay reglas|暂无规则|ルールはまだありません|아직 규칙이 없습니다|Henüz kural yok
result|Distribution|Распределение|Бөлу|Verteilung|Répartition|Distribución|分配结果|配分結果|배분 결과|Dağılım
allocated|Allocated|Распределено|Бөлінді|Verteilt|Réparti|Distribuido|已分配|配分済み|배분됨|Dağıtılan
remaining|Remaining|Осталось|Қалды|Verbleibend|Restant|Restante|剩余|残額|잔액|Kalan
shortfall|Shortfall|Не хватает|Жетіспейді|Fehlbetrag|Manque|Falta|缺口|不足額|부족액|Eksik tutar
required|Required|Нужно|Қажет|Benötigt|Nécessaire|Necesario|所需|必要額|필요액|Gereken
complete|Plan calculated|План рассчитан|Жоспар есептелді|Plan berechnet|Plan calculé|Plan calculado|计划已计算|計算完了|계산 완료|Plan hesaplandı
stopped|Stopped: not enough money|Остановка: не хватает денег|Тоқтады: ақша жетпейді|Gestoppt: Geld reicht nicht|Arrêt : fonds insuffisants|Detenido: saldo insuficiente|已停止：金额不足|停止：残額不足|중단: 잔액 부족|Durduruldu: para yetersiz
zeroStop|Stopped: zero balance|Остановка: нулевой остаток|Тоқтады: қалдық нөл|Gestoppt: Restbetrag null|Arrêt : solde nul|Detenido: saldo cero|已停止：余额为零|停止：残額ゼロ|중단: 잔액 0|Durduruldu: bakiye sıfır
simulationHint|This is a calculation. No money is transferred.|Это расчёт. Деньги никуда не переводятся.|Бұл есептеу ғана. Ақша аударылмайды.|Dies ist eine Berechnung. Es wird kein Geld überwiesen.|Ceci est un calcul. Aucun argent n’est transféré.|Es un cálculo. No se transfiere dinero.|这只是计算，不会转账。|計算のみです。送金は行いません。|계산만 수행하며 송금하지 않습니다.|Bu bir hesaplamadır. Para transfer edilmez.
language|Language|Язык|Тіл|Sprache|Langue|Idioma|语言|言語|언어|Dil
currency|Currency|Валюта|Валюта|Währung|Devise|Moneda|货币|通貨|통화|Para birimi
currencyHint|Display unit only. Changing currency does not convert amounts. No rates or internet needed.|Только единица отображения. Смена валюты не пересчитывает суммы. Курсы и интернет не нужны.|Тек көрсету бірлігі. Валютаны ауыстыру соманы өзгертпейді. Бағамдар мен интернет қажет емес.|Nur Anzeigeeinheit. Kein Umrechnen der Beträge, keine Kurse, kein Internet.|Unité d’affichage uniquement. Aucun montant converti, aucun taux ni internet requis.|Solo unidad de visualización. No convierte importes ni necesita tipos de cambio o internet.|仅改变显示单位，不换算金额。不需要汇率或网络。|表示単位のみ変更します。金額の換算や為替情報、通信は不要です。|표시 단위만 변경합니다. 금액 환산, 환율, 인터넷이 필요 없습니다.|Yalnızca gösterim birimi. Tutarlar dönüştürülmez. Kur veya internet gerekmez.
theme|Appearance|Оформление|Көрініс|Darstellung|Apparence|Apariencia|外观|外観|화면 테마|Görünüm
system|System|Как в системе|Жүйедегідей|System|Système|Sistema|跟随系统|システム|시스템|Sistem
light|Light|Светлое|Ашық|Hell|Clair|Claro|浅色|ライト|밝게|Açık
dark|Dark|Тёмное|Қараңғы|Dunkel|Sombre|Oscuro|深色|ダーク|어둡게|Koyu
backup|Your data|Твои данные|Сенің деректерің|Deine Daten|Vos données|Tus datos|你的数据|データ|내 데이터|Verilerin
backupHint|Stored in this browser on this device. Export a backup before clearing browser data or changing devices.|Хранятся в этом браузере на этом устройстве. Скачай копию перед очисткой браузера или сменой устройства.|Осы құрылғының браузерінде сақталады. Браузерді тазарту не құрылғыны ауыстыру алдында көшірме жүкте.|In diesem Browser auf diesem Gerät gespeichert. Vor dem Löschen der Browserdaten oder Gerätewechsel exportieren.|Stockées dans ce navigateur sur cet appareil. Exportez avant d’effacer le navigateur ou de changer d’appareil.|Guardados en este navegador y dispositivo. Exporta antes de borrar datos o cambiar de dispositivo.|数据保存在此设备的浏览器中。清除浏览器数据或更换设备前，请导出备份。|この端末のブラウザに保存します。データ削除や機種変更の前にバックアップしてください。|이 기기의 브라우저에 저장됩니다. 데이터 삭제나 기기 변경 전에 백업하세요.|Bu cihazın tarayıcısında saklanır. Tarayıcı verilerini silmeden veya cihaz değiştirmeden dışa aktar.
export|Export backup|Скачать копию|Көшірмені жүктеу|Sicherung exportieren|Exporter une copie|Exportar copia|导出备份|バックアップを書き出す|백업 내보내기|Yedeği dışa aktar
import|Import backup|Загрузить копию|Көшірмені жүктеп алу|Sicherung importieren|Importer une copie|Importar copia|导入备份|バックアップを読み込む|백업 가져오기|Yedeği içe aktar
history|Recovery history|История восстановления|Қалпына келтіру тарихы|Wiederherstellung|Historique de restauration|Historial de recuperación|恢复历史|復元履歴|복구 기록|Kurtarma geçmişi
historyHint|The last 20 states before changes. Local history is not a substitute for an exported backup.|Последние 20 состояний до изменений. Локальная история не заменяет скачанную копию.|Өзгеріске дейінгі соңғы 20 күй. Жергілікті тарих жүктелген көшірмені алмастырмайды.|Die letzten 20 Zustände vor Änderungen. Kein Ersatz für eine exportierte Sicherung.|Les 20 derniers états avant modification. Ne remplace pas une copie exportée.|Los últimos 20 estados antes de cambios. No sustituye una copia exportada.|保留修改前的最近20个状态。历史记录不能替代导出的备份。|変更前の状態を20件保存します。書き出したバックアップの代わりにはなりません。|변경 전 상태 20개를 보관합니다. 내보낸 백업을 대체하지 않습니다.|Değişiklik öncesi son 20 durum. Dışa aktarılan yedeğin yerine geçmez.
restore|Restore|Восстановить|Қалпына келтіру|Wiederherstellen|Restaurer|Restaurar|恢复|復元|복원|Geri yükle
noHistory|No changes yet|Изменений пока нет|Әзірге өзгерістер жоқ|Noch keine Änderungen|Aucune modification|Aún no hay cambios|暂无更改|変更履歴はありません|아직 변경 사항이 없습니다|Henüz değişiklik yok
confirmDelete|Delete “{name}”? You can recover it in Settings.|Удалить «{name}»? Восстановление доступно в настройках.|«{name}» жойылсын ба? Баптаулардан қалпына келтіруге болады.|„{name}“ löschen? Wiederherstellung in den Einstellungen.|Supprimer « {name} » ? Restauration dans les réglages.|¿Eliminar «{name}»? Puedes recuperarlo en Ajustes.|删除“{name}”？可在设置中恢复。|「{name}」を削除しますか？設定から復元できます。|“{name}”을 삭제할까요? 설정에서 복원할 수 있습니다.|“{name}” silinsin mi? Ayarlardan geri yüklenebilir.
confirmReplace|“{name}” already exists. Replace its rules?|«{name}» уже существует. Заменить его правила?|«{name}» бар. Ережелері ауыстырылсын ба?|„{name}“ existiert bereits. Regeln ersetzen?|« {name} » existe déjà. Remplacer ses règles ?|«{name}» ya existe. ¿Reemplazar sus reglas?|“{name}”已存在。替换其规则？|「{name}」は既に存在します。ルールを置き換えますか？|“{name}”이 이미 있습니다. 규칙을 바꿀까요?|“{name}” zaten var. Kuralları değiştirilsin mi?
confirmDiscard|Discard unsaved changes?|Отменить несохранённые изменения?|Сақталмаған өзгерістер жойылсын ба?|Ungespeicherte Änderungen verwerfen?|Abandonner les modifications ?|¿Descartar cambios sin guardar?|放弃未保存的更改？|未保存の変更を破棄しますか？|저장하지 않은 변경을 버릴까요?|Kaydedilmemiş değişiklikler silinsin mi?
confirmImport|Import {count} templates? {duplicates} existing names will be replaced. Other templates stay.|Загрузить шаблоны: {count}? Совпадающих имён будет заменено: {duplicates}. Остальные сохранятся.|{count} үлгі жүктелсін бе? Атауы бірдей {duplicates} үлгі ауыстырылады. Қалғаны сақталады.|{count} Vorlagen importieren? {duplicates} vorhandene Namen werden ersetzt. Andere bleiben.|Importer {count} modèles ? {duplicates} noms existants seront remplacés. Les autres restent.|¿Importar {count} plantillas? Se reemplazarán {duplicates} nombres existentes. Las demás se conservan.|导入{count}个模板？将替换{duplicates}个同名模板，其余保留。|{count}件を読み込みますか？同名の{duplicates}件を置き換え、他は残します。|템플릿 {count}개를 가져올까요? 같은 이름 {duplicates}개를 바꾸고 나머지는 유지합니다.|{count} şablon içe aktarılsın mı? Aynı adlı {duplicates} şablon değişir. Diğerleri kalır.
confirmRestore|Restore all templates to this state? The current state will be saved in history.|Вернуть все шаблоны к этому состоянию? Текущее состояние сохранится в истории.|Барлық үлгі осы күйге қайтарылсын ба? Қазіргі күй тарихта сақталады.|Alle Vorlagen auf diesen Stand setzen? Der aktuelle Stand wird gesichert.|Restaurer tous les modèles à cet état ? L’état actuel sera conservé.|¿Restaurar todas las plantillas a este estado? Se guardará el estado actual.|将所有模板恢复到此状态？当前状态将保留在历史中。|すべてをこの状態に戻しますか？現在の状態は履歴に保存されます。|모든 템플릿을 이 상태로 복원할까요? 현재 상태는 기록에 저장됩니다.|Tüm şablonlar bu duruma getirilsin mi? Mevcut durum geçmişe kaydedilir.
saved|Saved on this device|Сохранено на устройстве|Құрылғыда сақталды|Auf diesem Gerät gespeichert|Enregistré sur cet appareil|Guardado en este dispositivo|已保存在此设备|この端末に保存しました|이 기기에 저장됨|Bu cihaza kaydedildi
exported|Backup prepared|Копия подготовлена|Көшірме дайын|Sicherung vorbereitet|Copie préparée|Copia preparada|备份已准备|バックアップを準備しました|백업 준비됨|Yedek hazır
invalidNumber|Enter a non-negative number with up to 2 decimal places (max 999999999999.99).|Введи число от 0 до 999999999999,99, не более двух знаков после запятой.|0–999999999999,99 аралығындағы санды енгіз, үтірден кейін екі таңбаға дейін.|Zahl von 0 bis 999999999999,99 mit höchstens 2 Nachkommastellen eingeben.|Saisissez un nombre de 0 à 999999999999,99, avec 2 décimales maximum.|Introduce un número de 0 a 999999999999,99, con hasta 2 decimales.|请输入0至999999999999.99的数字，最多两位小数。|0〜999999999999.99、小数点以下2桁まで入力してください。|0~999999999999.99, 소수점 두 자리까지 입력하세요.|0–999999999999,99 arasında, en fazla 2 ondalıklı sayı gir.
invalidPercent|Percentage must be between 0 and 100.|Процент должен быть от 0 до 100.|Пайыз 0 мен 100 аралығында болуы керек.|Prozent muss zwischen 0 und 100 liegen.|Le pourcentage doit être entre 0 et 100.|El porcentaje debe estar entre 0 y 100.|百分比必须在0到100之间。|割合は0〜100で指定してください。|비율은 0~100이어야 합니다.|Yüzde 0 ile 100 arasında olmalı.
invalidDescription|Rule name must be 1–240 characters.|Название правила: от 1 до 240 символов.|Ереже атауы: 1–240 таңба.|Regelname: 1–240 Zeichen.|Nom de règle : 1 à 240 caractères.|Nombre de regla: 1–240 caracteres.|规则名称须为1至240个字符。|ルール名は1〜240文字です。|규칙 이름은 1~240자입니다.|Kural adı 1–240 karakter olmalı.
invalidTemplate|Enter a name (1–100 characters); up to 200 rules per template.|Введи название (1–100 символов); до 200 правил в шаблоне.|Атау енгіз (1–100 таңба); үлгіде 200 ережеге дейін.|Name mit 1–100 Zeichen; höchstens 200 Regeln je Vorlage.|Nom de 1 à 100 caractères ; 200 règles maximum par modèle.|Nombre de 1–100 caracteres; hasta 200 reglas por plantilla.|名称须为1至100个字符，每个模板最多200条规则。|名前は1〜100文字、ルールは200件までです。|이름은 1~100자, 규칙은 200개까지입니다.|Ad 1–100 karakter, şablon başına en fazla 200 kural.
invalidType|Unknown rule type.|Неизвестный тип правила.|Ереже түрі белгісіз.|Unbekannter Regeltyp.|Type de règle inconnu.|Tipo de regla desconocido.|未知规则类型。|不明なルールの種類です。|알 수 없는 규칙 유형입니다.|Bilinmeyen kural türü.
invalidBackup|Invalid backup. Use a Finlite JSON backup (up to 5 MB). Nothing was changed.|Некорректная копия. Нужен JSON Finlite до 5 МБ. Ничего не изменено.|Көшірме жарамсыз. 5 МБ дейінгі Finlite JSON қажет. Ештеңе өзгермеді.|Ungültige Sicherung. Finlite-JSON bis 5 MB verwenden. Nichts geändert.|Copie invalide. Utilisez un JSON Finlite de 5 Mo maximum. Rien n’a changé.|Copia no válida. Usa un JSON Finlite de hasta 5 MB. No se cambió nada.|备份无效。请使用不超过5 MB的Finlite JSON文件。未修改数据。|無効なバックアップです。5 MB以下のFinlite JSONを選んでください。変更はありません。|잘못된 백업입니다. 5 MB 이하의 Finlite JSON을 사용하세요. 변경되지 않았습니다.|Geçersiz yedek. En fazla 5 MB Finlite JSON kullan. Hiçbir şey değişmedi.
conflict|Data changed in another tab. Reload the list and try again; your draft is kept.|Данные изменились в другой вкладке. Обнови список и повтори; черновик сохранён.|Деректер басқа қойындыда өзгерді. Тізімді жаңартып, қайтала; нобай сақталды.|Daten in anderem Tab geändert. Liste neu laden; Entwurf bleibt erhalten.|Données modifiées dans un autre onglet. Actualisez ; le brouillon est conservé.|Datos cambiados en otra pestaña. Actualiza; se conserva tu borrador.|数据已在另一标签页更改。刷新列表后重试，草稿已保留。|別のタブで変更されました。一覧を更新してください。下書きは保持されます。|다른 탭에서 변경되었습니다. 목록을 새로 고치세요. 초안은 유지됩니다.|Veriler başka sekmede değişti. Listeyi yenile; taslak korunur.
nameExists|That name is already used. Choose another.|Это название уже занято. Выбери другое.|Бұл атау қолданылуда. Басқасын таңда.|Name bereits vergeben. Anderen wählen.|Ce nom existe déjà. Choisissez-en un autre.|Ese nombre ya existe. Elige otro.|名称已被使用，请选择其他名称。|この名前は使用中です。別の名前にしてください。|이미 사용 중인 이름입니다. 다른 이름을 선택하세요.|Bu ad kullanılıyor. Başka ad seç.
storageError|Could not save or read data. Check available storage and browser permissions. Export a backup if possible.|Не удалось сохранить или прочитать данные. Проверь свободное место и разрешения браузера. По возможности скачай копию.|Деректерді оқу не сақтау мүмкін болмады. Бос орын мен браузер рұқсаттарын тексер. Мүмкін болса көшірме жүкте.|Daten nicht lesbar oder speicherbar. Speicherplatz und Browserrechte prüfen. Wenn möglich Sicherung exportieren.|Lecture ou enregistrement impossible. Vérifiez l’espace et les autorisations. Exportez si possible.|No se pudo leer o guardar. Revisa espacio y permisos. Exporta una copia si puedes.|无法读写数据。请检查存储空间和浏览器权限，尽可能导出备份。|データを読み書きできません。空き容量と権限を確認し、可能ならバックアップしてください。|데이터를 읽거나 저장할 수 없습니다. 저장 공간과 권한을 확인하고 가능하면 백업하세요.|Veri okunamadı veya kaydedilemedi. Depolama ve tarayıcı izinlerini kontrol et. Mümkünse yedek al.
databaseBlocked|Close other Finlite tabs and reopen this page to finish the update.|Закрой другие вкладки Finlite и открой страницу заново для завершения обновления.|Жаңартуды аяқтау үшін басқа Finlite қойындыларын жауып, бетті қайта аш.|Andere Finlite-Tabs schließen und Seite neu öffnen.|Fermez les autres onglets Finlite et rouvrez cette page.|Cierra otras pestañas de Finlite y vuelve a abrir esta página.|请关闭其他Finlite标签页，然后重新打开此页完成更新。|他のFinliteタブを閉じ、このページを開き直してください。|다른 Finlite 탭을 닫고 이 페이지를 다시 여세요.|Diğer Finlite sekmelerini kapatıp bu sayfayı yeniden aç.
offlineReady|Ready offline|Готово без интернета|Офлайн жұмысқа дайын|Offline bereit|Prêt hors ligne|Listo sin conexión|可离线使用|オフライン準備完了|오프라인 준비됨|Çevrimdışı hazır
offlinePreparing|Preparing offline access…|Подготовка офлайн-доступа…|Офлайн қолжетімділік дайындалуда…|Offline-Zugriff wird vorbereitet…|Préparation du mode hors ligne…|Preparando acceso sin conexión…|正在准备离线访问…|オフラインを準備中…|오프라인 준비 중…|Çevrimdışı erişim hazırlanıyor…
offlineFailed|Offline setup failed. Reopen online to retry.|Офлайн-доступ не подготовлен. Открой с интернетом для повтора.|Офлайн дайындалмады. Қайталау үшін интернетпен аш.|Offline-Einrichtung fehlgeschlagen. Mit Internet erneut öffnen.|Échec du mode hors ligne. Rouvrez avec internet.|Falló la preparación sin conexión. Abre con internet para reintentar.|离线设置失败，请联网重新打开重试。|オフライン準備に失敗しました。オンラインで開き直してください。|오프라인 설정 실패. 인터넷 연결 후 다시 여세요.|Çevrimdışı hazırlık başarısız. İnternetle yeniden aç.
install|Install app|Установить приложение|Қолданбаны орнату|App installieren|Installer l’application|Instalar aplicación|安装应用|アプリをインストール|앱 설치|Uygulamayı yükle
installHint|Open the browser menu → Install app / Add to Home Screen. First open needs HTTPS or localhost; later launches work offline.|Меню браузера → Установить / На экран «Домой». Первое открытие — через HTTPS или localhost; затем можно без интернета.|Браузер мәзірі → Орнату / Басты экранға қосу. Алғаш рет HTTPS не localhost арқылы аш; кейін офлайн жұмыс істейді.|Browsermenü → Installieren / Zum Startbildschirm. Erster Aufruf über HTTPS oder localhost, danach offline.|Menu du navigateur → Installer / Sur l’écran d’accueil. Premier accès via HTTPS ou localhost, puis hors ligne.|Menú del navegador → Instalar / Añadir a inicio. Primero HTTPS o localhost; después funciona sin conexión.|浏览器菜单→安装应用／添加到主屏幕。首次需通过HTTPS或localhost打开，之后可离线使用。|ブラウザのメニュー→インストール／ホーム画面に追加。初回はHTTPSかlocalhostで開き、以後はオフラインで使えます。|브라우저 메뉴 → 설치 / 홈 화면에 추가. 처음에는 HTTPS 또는 localhost로 열고 이후 오프라인으로 사용하세요.|Tarayıcı menüsü → Yükle / Ana ekrana ekle. İlk açılış HTTPS veya localhost ile, sonrası çevrimdışı.
updateReady|An update is ready.|Доступно обновление.|Жаңарту дайын.|Update verfügbar.|Mise à jour disponible.|Hay una actualización.|有更新可用。|更新があります。|업데이트가 있습니다.|Güncelleme hazır.
update|Update app|Обновить приложение|Қолданбаны жаңарту|App aktualisieren|Mettre à jour|Actualizar|更新应用|更新する|앱 업데이트|Uygulamayı güncelle
refresh|Refresh list|Обновить список|Тізімді жаңарту|Liste aktualisieren|Actualiser la liste|Actualizar lista|刷新列表|一覧を更新|목록 새로 고침|Listeyi yenile
close|Close|Закрыть|Жабу|Schließen|Fermer|Cerrar|关闭|閉じる|닫기|Kapat
loading|Loading…|Загрузка…|Жүктелуде…|Laden…|Chargement…|Cargando…|加载中…|読み込み中…|불러오는 중…|Yükleniyor…
`;
export const messages = Object.fromEntries(Object.keys(languages).map(code => [code, {}]));
for (const row of rows.trim().split('\n')) {
    const [key, ...values] = row.split('|');
    if (values.length !== 10) throw new Error('Translation count: ' + key);
    Object.keys(languages).forEach((code, i) => { messages[code][key] = values[i]; });
}
export function translate(language, key, params = {}) {
    let text = messages[language]?.[key] ?? messages.en[key] ?? key;
    for (const [name, value] of Object.entries(params)) text = text.replaceAll('{' + name + '}', String(value));
    return text;
}
